# Copyright (C) 2021, Yubao Liu, AISL, TOYOHASHI UNIVERSITY of TECHNOLOGY 
# Email: yubao.liu.ra@tut.jp 
version: '2.3'
services:
  multicol_slam:
    image: yubao/multicol_slam
    container_name: multicol_slam
    build:
        context: .
        # args:
        #     - HTTP_PROXY=$HTTP_PROXY
        #     - http_proxy=$HTTP_PROXY
        #     - HTTPS_PROXY=$HTTPS_PROXY
        #     - https_proxy=$HTTPS_PROXY
    command:  lxterminal
    # command:  bash
    runtime: nvidia
    privileged: true
    stdin_open: true
    tty: true
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ..:/home/ubuntu/catkin_ws/src/MultiCol-SLAM
        - ${DATASET_DIR}:/home/ubuntu/dataset
        - ~/.vim:/home/ubuntu/.vim
        - multicol_slam_root:/home/ubuntu
        # - ./extern:/home/ubuntu/extern
    entrypoint: /ros_entrypoint.sh
    network_mode: host
    dns:
        - 8.8.8.8
        - 4.4.4.4

volumes:
    multicol_slam_root:
